---
- hosts: all
  sudo: yes
  tasks:
  - name: install packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items: 
 - git
 - php
 - php-cli
 - php-mysql
 -php-zip
 - php-json 
 -php-gd
 - php-mbstring
 - php-curl 
 - php-xml
 - php-pear
 - php-bcmath 
 - php-pdo
 - openssl
 - apache2 
 - libapache2-mod-php
 - unzip
 -nano
 - mysql-server
 -mysql-client 


- name: Clone git repository
git: >
dest=/octoberdev93
repo=https://github.com/antonzv93/octoberdev93.git
update=no
sudo: yes
sudo_user: www-data
register: cloned
mode:0755

vars:
source_files:   ./octoberdev93/
destin_file: /var/www/html/



tasks: Copy pages to server:
- name: Copy to Mywebserver
  copy:  src={{ source_file }}    dest={{ destin_file }}
  mode=0755
   notify: Restart Apache

- name: Start serverweb
  service: name=apache2 state=started enabled=yes 


handlers:
- name: Restart Apache
  service: name=apache2 state=restarted
