---
- hosts: localhost
  remote_user: root 
  become: yes
  
tasks:
- name: Creates directory
    file: path=/var/www/{{ domain }} state=directory
    sudo: yes

- name: Download octoberdev93
    git:
     repo: https:/github.com/antonzv93/octoberdev93.git
     dest=/var/www/html
     validate_certs=no
     version: master
     become: yes
     mode: 0755
  

- name: Deploy Apache2 and other
  hosts: localhost
  become: yes
  become_method: sudo
  roles:
   - apache2
   - php-fpm
   - mysql
    
