---
- hosts: localhost
  connection: local
  become: yes
  
  tasks:

  - name: Install git
  apt: name=git state=latest

  

  - name: Download octoberdev93
    git:
      repo: 'https:/github.com/antonzv93/octoberdev93.git'
      dest: /etc/ansible/gce
      
      
